BaSP-TG-7:  Employee Entity
BaSP-m2022/agustin-trackgenix-server pull request #17
Opened 2022-05-16 14:09 UTC by CristianAlcober

2022-05-16 19:17 UTC, GinaSchP reviewed
falta la validación antes del create. También borrar los comentarios

2022-05-17 21:09 UTC, AgustinCarthery approved these changes

2022-05-18 00:15 UTC, GuidoCerioni requested changes
Deberiamos cambiar las responses de la validacion de JOI (ver slack)

2022-05-18 02:20 UTC, CristianAlcober commented on src/validations/employees.js
> +      error: validate.error.details[0].message,
Just updated!

2022-05-18 02:21 UTC, GuidoCerioni approved these changes
Nice! Well done.

2022-05-18 21:16 UTC, AgustinCarthery approved these changes

2022-05-19 13:30 UTC, merged