BaSP-TG-8: task entity
BaSP-m2022/agustin-trackgenix-server pull request #18
Opened 2022-05-16 14:19 UTC by Clarosluciano

# Branch: feature/TG-8/task-luciano

- [x] Controllers: tasks js doc created
- [x] Models: Tasks js doc created
- [x] Routes: tasks js doc created
- [x] Validations: tasks js doc created

2022-05-16 19:46 UTC, Clarosluciano commented on src/routes/tasks.js
> +  .put('/:id', tasksController.updateTask)
Tenés razón jajaja por algo le había puesto ese nombre que bobi

2022-05-16 21:13 UTC, Clarosluciano commented on src/routes/tasks.js
> +  .put('/:id', tasksController.updateTask)
Listo, agregado

2022-05-17 13:53 UTC, CristianAlcober approved these changes

2022-05-17 21:08 UTC, AgustinCarthery approved these changes

2022-05-18 00:07 UTC, GuidoCerioni requested changes
Deberiamos cambiar las responses de la validacion de JOI (ver slack) ;)

2022-05-18 00:36 UTC, AgustinCarthery requested changes

2022-05-18 00:36 UTC, AgustinCarthery commented on src/validations/tasks.js
> +      msg: 'There was an error while the validation was requested',
update response format with {msg, data, error}

2022-05-18 00:36 UTC, AgustinCarthery commented on src/validations/tasks.js
> +
A separate Update validation must be required in order to avoid prompting the user to fill in all properties under a required properties schema

2022-05-18 15:16 UTC, GuidoCerioni approved these changes
I corrected the same Agustin did. I approve my review.

2022-05-18 21:15 UTC, AgustinCarthery approved these changes

2022-05-18 21:15 UTC, merged