BaSP-TG-5: Admin Entity.
BaSP-m2022/agustin-trackgenix-server pull request #19
Opened 2022-05-17 18:28 UTC by gregorioelias

#Branch: feature/TG-5/admin-gregorio

-[]Controllers: admin js doc created
-[] Models: admin js doc created
-[]Routes: admin js doc created
-[]Validations: admin js doc created

2022-05-17 21:07 UTC, AgustinCarthery approved these changes

2022-05-17 23:26 UTC, GuidoCerioni reviewed
Excelente Grego!!! Solo vi una cosita en la validación del Joi, que a una password le pusiste min(6) y a la otra min(8)

2022-05-18 00:16 UTC, GuidoCerioni requested changes
Deberiamos cambiar las responses de la validacion de JOI (ver slack)

2022-05-18 00:29 UTC, GuidoCerioni approved these changes
Excelente laburo animal, sos un capo, a seguir asi por este camino

2022-05-18 01:36 UTC, merged